"""
Regenerates src/game/imageEquivalence.generated.ts.

Two image-puzzle answers are the same answer when they turn every example
picture of the puzzle into exactly the same output picture. The website uses
that to (a) reject a submission equivalent to one already posted and (b) mark
every ordering that reproduces the correct output as right.

This runs the CLI's own transforms (blackbox-ml-game) over every pipeline a team
can submit (each transform at most once, up to as many steps as the correct
answer) and records the groups of pipelines that give identical pixels.

Re-run it whenever a curated picture, a transform, or an image puzzle changes in
blackbox-ml-game:

    cd blackbox-ml-game
    uv run python ../scripts/gen_image_equivalence.py
"""

from __future__ import annotations

import hashlib
import sys
from itertools import permutations
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "blackbox-ml-game" / "src"))

from blackbox_game.images import IMAGE_TRANSFORMS, PIPELINES, load_curated, pipeline_commutes  # noqa: E402
from blackbox_game.puzzles import PUZZLE_REGISTRY, puzzle_number  # noqa: E402

OUT = ROOT / "src" / "game" / "imageEquivalence.generated.ts"

ORDER = list(IMAGE_TRANSFORMS)           # a transform's code letter is its index here: a, b, c, ...


def code(names: list[str]) -> str:
    return "".join(chr(97 + ORDER.index(n)) for n in names)


def correct_steps(puzzle) -> list[str]:
    transform = puzzle.function.parameters["transform"]
    return list(PIPELINES[transform][1]) if transform in PIPELINES else [transform]


def groups_for(images: list[str], max_steps: int) -> dict[str, str]:
    """Every pipeline of distinct transforms, 1..max_steps long -> hash of its output pictures."""
    digest_of: dict[str, str] = {}

    def walk(prefix: str, outputs) -> None:
        for i, name in enumerate(ORDER):
            letter = chr(97 + i)
            if letter in prefix:
                continue
            nxt = [IMAGE_TRANSFORMS[name](o) for o in outputs]
            pipeline = prefix + letter
            digest_of[pipeline] = hashlib.sha256(b"".join(a.tobytes() for a in nxt)).hexdigest()
            if len(pipeline) < max_steps:
                walk(pipeline, nxt)

    walk("", [load_curated(n) for n in images])
    return digest_of


def main() -> None:
    result: dict[str, list[list[str]]] = {}

    for pid, puzzle in PUZZLE_REGISTRY.items():
        if puzzle.function.type != "image":
            continue
        puzzle_id = f"puzzle_{puzzle_number(pid):02d}"
        steps = correct_steps(puzzle)
        digest_of = groups_for(puzzle.function.parameters["images"], len(steps))

        by_digest: dict[str, list[str]] = {}
        for pipeline, digest in digest_of.items():
            by_digest.setdefault(digest, []).append(pipeline)
        groups = sorted(sorted(g) for g in by_digest.values() if len(g) > 1)
        result[puzzle_id] = groups

        right = by_digest[digest_of[code(steps)]]
        names = [" > ".join(ORDER[ord(c) - 97] for c in p) for p in sorted(right)]
        print(f"{puzzle_id} ({pid}): {len(digest_of)} pipelines, {len(groups)} groups with >1 member")
        print(f"    accepted as right ({len(right)}): {names}")

        # Cross-check against the CLI's own commutativity test.
        if len(steps) > 1 and pid in PIPELINES:
            all_orders_right = all(code(list(p)) in right for p in permutations(steps))
            assert all_orders_right == pipeline_commutes(pid), f"{pid}: disagrees with pipeline_commutes"

    lines = [
        "// AUTO-GENERATED by scripts/gen_image_equivalence.py. Do not edit by hand.",
        "// Each inner array is a set of pipelines that give identical output pictures for that puzzle.",
        "// A pipeline is written as one letter per transform, the letter being its index in TRANSFORM_ORDER.",
        "",
        "export const TRANSFORM_ORDER = [",
        *[f"  '{name}'," for name in ORDER],
        "] as const",
        "",
        "export const EQUIVALENT_PIPELINES: Record<string, string[][]> = {",
    ]
    for puzzle_id, groups in result.items():
        lines.append(f"  {puzzle_id}: [")
        lines += [f"    [{', '.join(repr(p) for p in g)}]," for g in groups]
        lines.append("  ],")
    lines += ["}", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
